modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="cobreacy"
version="${mod_version}"
displayName="Cobreacy"
authors="HO-Artisan"
description='''${mod_description}'''
[[dependencies.cobreacy]]
   modId="forge"
   mandatory=true
   versionRange="[47,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.cobreacy]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1,1.21)"
   ordering="NONE"
   side="BOTH"
